# -*- coding: utf-8 -*-
"""Project_Car_Game_Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJ1ubnEgiytyr2WMpsUGr_XCx6B_gbhU

# Project: Car Game Simulation
## Description: A text-based car game using Python

This is python program to simulate a simple car game where the user can control the car using text-based commands.

Follow the instructions below:

1. Commands: The program should accept the following commands:

* start: To start the car.

* stop: To stop the car.

* help: To display the list of available commands.

* quit: To exit the game.

2. Responses:

* If the car is already started and the user types start, display "Car is already started!".

* If the car is already stopped and the user types stop, display "Car is already stopped!".

* Typing start when the car is stopped should display "Car Started...Ready to Go!" and mark the car as started.

* Typing stop when the car is started should display "Car Stopped." and mark the car as stopped.

* Typing help should display the list of commands in the following format:

  a. start -> to start the car

  b. stop -> to stop the car

  c. quit -> to exit

* Typing anything other than the allowed commands should display "Sorry, I don't Understand!".


3. Termination: The program should terminate when the user types quit.
"""

command = ""
Car_Started = False
while True:
  command = input("enter the commmand: ").lower()
  if command.lower() == "start":
    if Car_Started:
      print("Car is already started!")
    else:
      Car_Started = True
      print("Car Started...Ready to Go!")
  elif command.lower() == "stop":
    if not Car_Started:
      print("Car is already stopped!")
    else:
      Car_Started = False
      print("Car Stopped.")
  elif command.lower() == "help":
    print("""
    start -> to start the car
    stop -> to stop the car
    quit -> to exit
    """)
  elif command.lower() == "quit":
    break;
  else:
    print("Sorry, I don't Understand!")

"""## -----------------------------------------------------------------------
## Thank you for using this program!
## Feel free to reach out for collaboration or feedback.
## LinkedIn: https://www.linkedin.com/in/khushi-jhamb/
## Email: 39khushi@gmail.com
##-----------------------------------------------------------------------
"""

